# Generated by Django 3.1.3 on 2020-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('listings', models.ManyToManyField(blank=True, related_name='usernames', to='auctions.Listing')),
            ],
        ),
    ]
