# Generated by Django 3.1.3 on 2021-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210102_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=56),
        ),
    ]
