# Generated by Django 3.1.3 on 2021-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210105_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='username', to='auctions.Listing'),
        ),
    ]
