# Generated by Django 3.1.3 on 2021-01-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_username_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='watchlist',
            new_name='product',
        ),
    ]
