# Generated by Django 3.1.3 on 2021-01-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210107_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Listing'),
        ),
    ]
