# Generated by Django 3.1.3 on 2021-01-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auctions.product'),
        ),
    ]
