# Generated by Django 3.1.3 on 2021-01-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210128_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='auctions.username')),
            ],
        ),
    ]
