# Generated by Django 3.1.3 on 2021-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210130_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default=None, max_length=56),
        ),
    ]
