# Generated by Django 3.1.3 on 2021-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210120_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='offer',
        ),
        migrations.AddField(
            model_name='bid',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='bid', to='auctions.Listing'),
        ),
    ]
