# Generated by Django 3.1.3 on 2021-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210131_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
