# Generated by Django 3.1.3 on 2021-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210120_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='initial',
            field=models.IntegerField(default=None),
        ),
    ]
