# Generated by Django 3.1.3 on 2021-02-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_product_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highest_bidder',
        ),
    ]
