# Generated by Django 3.1.3 on 2021-02-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_product_highest_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_bid', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.username')),
            ],
        ),
    ]
