# Generated by Django 3.1.3 on 2021-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='initial',
            field=models.IntegerField(),
        ),
    ]
