# Generated by Django 3.1.3 on 2021-01-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210121_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init', to='auctions.listing'),
        ),
    ]
