# Generated by Django 3.1.3 on 2021-02-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentary',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.username'),
        ),
    ]
