# Generated by Django 3.1.3 on 2021-01-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210121_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='bid',
            name='initial_bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='auctions.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentary',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Product'),
        ),
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Product'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
