# Generated by Django 3.1.3 on 2021-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.ImageField(upload_to='products'),
        ),
    ]
