# Generated by Django 3.1.3 on 2021-01-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='initial_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
