# Generated by Django 3.1.3 on 2021-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210121_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='initial_bid',
            field=models.IntegerField(),
        ),
    ]
