# Generated by Django 3.1.3 on 2021-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210121_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='initial_bid',
        ),
        migrations.AddField(
            model_name='product',
            name='initial_bid',
            field=models.IntegerField(default=None),
        ),
    ]
