# Generated by Django 3.1.3 on 2021-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210121_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='initial_bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='auctions.product'),
        ),
    ]
