# Generated by Django 3.1.3 on 2021-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210203_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=56)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
