# Generated by Django 3.1.3 on 2021-01-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210122_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='initial_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='auctions.product'),
        ),
    ]
