# Generated by Django 3.1.3 on 2021-02-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210204_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auctions.product'),
        ),
    ]
