# Generated by Django 3.1.3 on 2021-02-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210204_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auctions.product'),
        ),
    ]
